### ISSUE TITLE
Error in 0.18 tree

### ISSUE THREAD

**Issue by reyder** [SimosMCmuffin/FlexiBMS_Lite_FW#10]
It seems that 0.18 tree does not compile:

https://github.com/SimosMCmuffin/FlexiBMS_Lite_FW/tree/0.18

because of this:

[SimosMCmuffin/FlexiBMS_Lite_FW/blob/0.18/Src/AuxFunctions.c#L394](https://github.com/SimosMCmuffin/FlexiBMS_Lite_FW/blob/0.18/Src/AuxFunctions.c#L394)

also off topic question. Is there a reason why posted .bin(s) are compiled in DEBUG mode ?

**Comment by SimosMCmuffin** [comment]
I just pushed 0.19 FW release out, so you might want to pull the latest commit.

---

What error message do you specifically get on the 0.18 FW's AuxFunctions.c#L394 ?

Good thing you pointed out that I had been releasing the binaries of the debug build instead on release. I had been completely on auto-pilot when posting the release binaries and accidentally always picking them from the debug build folder. 

The latest 0.19 FW binaries are now from the release build, thank you.

**Comment by mkulikf5** [comment]
I compiled 0.19 few days ago and it seems to works fine. I will start testing it more thoroughly in a couple of weeks.

I don't remember error msg but you are checking runtimePars.chargingState for two different values with AND so it will never be true.

It is already fixed by you in master by commenting: `runtimePars.chargingState == notCharging` I'm not sure why it's not in 0.18 tree probably by accident. 😄

**Comment by reyder** [comment]
I compiled 0.19 few days ago and it seems to works fine. I will start testing it more thoroughly in a couple of weeks.

I don't remember error msg but you are checking runtimePars.chargingState for two different values with AND so it will never be true.

It is already fixed by you in master by commenting: runtimePars.chargingState == notCharging I'm not sure why it's not in 0.18 tree probably by accident. 😄

**Comment by SimosMCmuffin** [comment]
"It is already fixed by you in master by commenting: runtimePars.chargingState == notCharging I'm not sure why it's not in 0.18 tree probably by accident. smile"

I looked and wondered the same thing when I compared it to my current code.

**Comment by SimosMCmuffin** [comment]
If you find more errors or have questions, open a new issue, thank you.
