### ISSUE TITLE
Serial interface not accepting commands

### ISSUE THREAD

**Issue by b264** [SimosMCmuffin/FlexiBMS_Lite_FW#9]
Trying to connect to FlexiBMS Lite 12S 1.0, I’m not able to issue any commands.

```
b264@computer:~$ cu -l /dev/ttyACM0 -s 115200
Connected.


Invalid command, type "$?" for command list


Invalid command, type "$?" for command list


Invalid command, type "$?" for command list


Invalid command, type "$?" for command list
```

Anytime I press any key, it immediately responds with `Invalid command, type "$?" for command list` without waiting for me to finish typing or even press enter.

Any keypress immediately responds with error. Any key on the keyboard. (except, it seems, Ctrl+Shift+J)

This is using 115200 baud, 8 data bits, 1 stop bit, no parity, XON/XOFF flow control

No combination of newline settings change anything.

Using PuTTY or another application to connect does not help.

**Comment by b264** [comment]
This was solved by using `picocom --baud=115200 --flow=soft --parity=none --databits=8 --stopbits=1 /dev/ttyACM0` instead of `cu`, `screen`, PuTTY, or any of the others I tried

**Comment by SimosMCmuffin** [comment]
Issue solved.
